version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      allow:
          - dependency-name: "@turbowarp/*"
          - dependency-name: "@AmpM0d/*"
          - dependency-name: "scratch-audio"
          - dependency-name: "scratch-render"
          - dependency-name: "scratch-vm"
          - dependency-name: "scratch-paint"
          - dependency-name: "scratch-blocks"
