/* generated by pull.js */
const manifest = {
  "noTranslations": true,
  "name": "Remove AmpMod Forums button",
  "description": "Removes the link to the AmpMod Forums from the menu bar.",
  "userstyles": [
    {
      "url": "remove-feedback.css"
    }
  ],
  "tags": [
    "danger"
  ],
  "dynamicDisable": true,
  "enabledByDefault": false
};
export default manifest;
