name: Build

on:
    push:
        branches: develop
    pull_request:
    workflow_dispatch:

jobs:
    build:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  persist-credentials: false
            - name: Install Node.js
              uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
              with:
                  node-version: 20
                  cache: npm
            - run: npm ci
            - run: |
                  rm .gitignore
                  cp builds-gitignore .gitignore
            - run: |
                  git branch -D developBuilds || true
                  git branch developBuilds
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add block*.js
                  git add .gitignore
            - run: git commit -m "Updating build"
            - run: git restore .
            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  force: true
                  branch: developBuilds
                  directory: .
                  github_token: ${{ secrets.GITHUB_TOKEN }}
