/* generated by pull.js */
const manifest = {
  "name": "Delete other assets",
  "description": "Adds an option to the right click menu to easily delete all other costumes, backdrops, or sounds.",
  "tags": [
    "recommended",
    "new"
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "credits": [
    {
      "name": "Jazza",
      "link": "https://scratch.mit.edu/users/greeny--231"
    }
  ],
  "dynamicDisable": true
};
export default manifest;
