name: Build (Auto)

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
                  persist-credentials: false
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
            - name: Install dependencies
              run: npm ci
            - name: Prepare extensions
              # Don't need to do a full fetch, that would just cause a lot of unnecessary traffic
              run: node scripts/prepare-extensions.js
            - name: Compile
              run: pnpm run webpack:compile
            - name: Package
              run: pnpm run electron:package:dir
